### ISSUE TITLE
bower install

### ISSUE THREAD

**Issue by 4play** [swetorrentking/rartracker#14]
I have problem with this:

root@server:/var/www# bower install

TypeError: Object #<Object> has no method 'toLowerCase'
    at Function.Buffer.isEncoding (buffer.js:245:32)
    at assertEncoding (fs.js:98:27)
    at Object.fs.writeFileSync (fs.js:908:3)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/bower/lib/node_modules/write-file-atomic/index.js:37:8)
    at Object.create.all.set (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:63:21)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:11)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:456:26)

how to fix this ?
I using Debian OS

**Comment by swetorrentking** [comment]
Not sure why. Maybe the NodeJS/NPM version is old, try installing the latest.

**Comment by 4play** [comment]
i upgrade bower, NodeJS/NPM and its the same problem :/

**Comment by 4play** [comment]
I solved this problem i make reinstall and all this upgrading on the lastes version
