### ISSUE TITLE
Gulp issue?

### ISSUE THREAD

**Issue by k0nsl** [swetorrentking/rartracker#41]
I'll create a new issue rather than piling on at one of the closed ones. I've got a problem when running the last commands:
```
npm install && npm run
```
I've tried this on both Debian and Centos and it yields only the following:
```
[root@srv51 rartracker]# npm install && npm run dist
npm WARN lifecycle rartracker@0.3.2~postinstall: cannot run in wd %s %s (wd=%s) rartracker@0.3.2 bower install /home/user/rartracker
npm WARN rartracker@0.3.2 No repository field.
npm WARN rartracker@0.3.2 No license field.

> rartracker@0.3.2 dist /home/user/rartracker
> gulp dist

[02:18:11] Using gulpfile /home/user/rartracker/gulpfile.js
[02:18:11] Starting 'lint'...
[02:18:11] Starting 'dist-html'...
[02:18:11] Starting 'libs'...
[02:18:11] Starting 'css'...
[02:18:11] Starting 'copy-fonts'...
[02:18:11] Finished 'copy-fonts' after 482 μs
[02:18:11] Finished 'libs' after 22 ms
/home/user/rartracker/node_modules/copy-dir/index.js:218
    var dirs = list.dirs.map(function(v) {
                   ^

TypeError: Cannot read property 'dirs' of undefined
    at /home/user/rartracker/node_modules/copy-dir/index.js:218:20
    at /home/user/rartracker/node_modules/copy-dir/index.js:21:21
    at FSReqWrap.oncomplete (fs.js:111:15)

npm ERR! Linux 3.10.0-427.18.2.lve1.4.24.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rartracker@0.3.2 dist: `gulp dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rartracker@0.3.2 dist script 'gulp dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rartracker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rartracker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rartracker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/rartracker/npm-debug.log
```
Versions:
```
[root@srv51 rartracker]# node --version
v7.2.1
[root@srv51 rartracker]# npm --version
3.10.10
```
Any ideas?

**Comment by k0nsl** [comment]
Fixed.
