### ISSUE TITLE
rartracker@0.3.2 dist: `gulp dist`

### ISSUE THREAD

**Issue by valsha** [swetorrentking/rartracker#52]
> gulp dist

[18:04:33] Using gulpfile ~/rartracker-master/gulpfile.js
[18:04:33] Starting 'lint'...
[18:04:33] Starting 'dist-html'...
[18:04:33] Starting 'libs'...
[18:04:33] Starting 'css'...
[18:04:33] Starting 'copy-fonts'...
[18:04:33] Finished 'copy-fonts' after 817 μs
[18:04:33] Finished 'libs' after 40 ms
/root/rartracker-master/node_modules/copy-dir/index.js:218
    var dirs = list.dirs.map(function(v) {
                   ^

TypeError: Cannot read property 'dirs' of undefined
    at /root/rartracker-master/node_modules/copy-dir/index.js:218:20
    at /root/rartracker-master/node_modules/copy-dir/index.js:21:21
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 4.10.0-19-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! rartracker@0.3.2 dist: `gulp dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rartracker@0.3.2 dist script 'gulp dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rartracker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rartracker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rartracker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/rartracker-master/npm-debug.log

**Comment by valsha** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dist' ]
2 info using npm@3.5.2
3 info using node@v4.7.2
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle rartracker@0.3.2~predist: rartracker@0.3.2
6 silly lifecycle rartracker@0.3.2~predist: no script for predist, continuing
7 info lifecycle rartracker@0.3.2~dist: rartracker@0.3.2
8 verbose lifecycle rartracker@0.3.2~dist: unsafe-perm in lifecycle true
9 verbose lifecycle rartracker@0.3.2~dist: PATH: /usr/share/npm/bin/node-gyp-bin:/root/rartracker-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle rartracker@0.3.2~dist: CWD: /root/rartracker-master
11 silly lifecycle rartracker@0.3.2~dist: Args: [ '-c', 'gulp dist' ]
12 silly lifecycle rartracker@0.3.2~dist: Returned: code: 1  signal: null
13 info lifecycle rartracker@0.3.2~dist: Failed to exec dist script
14 verbose stack Error: rartracker@0.3.2 dist: `gulp dist`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:854:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
15 verbose pkgid rartracker@0.3.2
16 verbose cwd /root/rartracker-master
17 error Linux 4.10.0-19-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist"
19 error node v4.7.2
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error rartracker@0.3.2 dist: `gulp dist`
22 error Exit status 1
23 error Failed at the rartracker@0.3.2 dist script 'gulp dist'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the rartracker package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp dist
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs rartracker
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls rartracker
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Mga-Denmark** [comment]
Did you remember to create all folders described in the readme.md? Like dist etc. And are they writeable? What about bower install did it go thrue?

**Comment by valsha** [comment]
I don't see any info in readme.md about manualy creating folders like "dist", or any other. 
Only permission ro torrents/ subs/ and img/imdb/
Yes, i did install bower (install --global bower).

**Comment by Mga-Denmark** [comment]
Did yoy try 'bower install' to fetch depencies?

Den 18. apr. 2017 9.44 AM skrev "valsha.github.io" <notifications@github.com

**Comment by Mga-Denmark** [comment]
What does the output of nodejs & npm say?:
nodejs --version
npm --version

Try redo all steps:

1) mkdir TestFolder
2) cd TestFolder
3) npm install --global bower
4) npm install --global gulp-cli
5) git clone https://github.com/swetorrentking/rartracker.git .
6) mkdir torrents subs img/imdb/
7) npm install
8) bower install --allow-root
9) npm run dist

This works for me on debian, using nodejs 7.9 and npm 4.2.0.

**Comment by valsha** [comment]
Thanks, let me check. I am using ubuntu 17.04 x32

**Comment by valsha** [comment]
nodejs --version
v4.7.2
npm --version
3.5.2

[09:33:43] Using gulpfile ~/torrent/gulpfile.js
[09:33:43] Starting 'lint'...
[09:33:43] Starting 'dist-html'...
[09:33:43] Starting 'libs'...
[09:33:43] Starting 'css'...
[09:33:43] Starting 'copy-fonts'...
[09:33:43] Finished 'copy-fonts' after 1.99 ms
[09:33:43] Finished 'css' after 578 ms
[09:33:43] Finished 'libs' after 742 ms
[09:33:47] Finished 'dist-html' after 4.5 s
[09:33:50] Finished 'lint' after 7 s
[09:33:50] Starting 'dist-js'...
[09:34:03] Finished 'dist-js' after 13 s
[09:34:03] Starting 'dist'...
[09:34:03] Finished 'dist' after 28 μs

all is ok now?

**Comment by Mga-Denmark** [comment]
Great!

just remember to chmod + chown the folders correctly.

like chown -Rv www-data:www-data *

**Comment by valsha** [comment]
have i question :)
now i need point apache (virtual name) to this TestFolder as my DocumentRoot folder?

**Comment by Mga-Denmark** [comment]
This is really not a support ticket.... But here goes...

I use Nginx and php-fpm my self, so I can't remember of the top of my head.

But try look inside /etc/apache2/sites-available/
there you should find a default file, inside it it should show you how to do it!

also do if you make a copy of this file, remember to link it to a file inside /etc/apache2/sites-enabled/

and do check that mod_php5 is installed and loaded in apaches config files, and also mod_rewrite look in /etc/apache2/conf.d/ folder i belive.

**Comment by valsha** [comment]
all is fine, but i have a new ...error :)

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL /api/v1/auth was not found on this server.</p> <hr> <address>Apache/2.4.10 (Debian) Server at torrent.com Port 80</address> </body></html> `

when i am trying to login using - named "System" password: "password"

**Comment by Mga-Denmark** [comment]
The htaccess file is not used, or mod rewrite is nok loaded.

Den 18. apr. 2017 5.24 PM skrev "valsha.github.io" <notifications@github.com

**Comment by valsha** [comment]
```
a2enmod rewrite
Module rewrite already enabled
```

and i just try 

```
 wget -O /dev/null http://127.0.0.1/api/v1/run-statistics
--2017-04-18 16:13:10--  http://127.0.0.1/api/v1/run-statistics
Connecting to 127.0.0.1:80... connected.
HTTP request sent, awaiting response... 404 Not Found
```
is this ok? 
looks like server (nodejs) is not running.

**Comment by Mga-Denmark** [comment]
there is no nodejs server,

there is static html and javascripts for the browser, that needs to be served by what ever http server you want to run.  and then there are php scripts that needs a http server with a php interpreter,

**Comment by markim** [comment]
Lol you have the patience of a saint @Mga-Denmark

**Comment by Mga-Denmark** [comment]
@markim my old userbase will not likely agree with you there =p

But I try to better my self, in the event that I would rejoin the world of torrenting ;)
